### ISSUE TITLE
an error has occurred /... this most time happened after update telegram

### ISSUE THREAD

**Issue by shit2live** [SpriteOvO/Telegram-Anti-Revoke#95] opened 2021-12-08 22:24 UTC
### Steps to reproduce
1. 
2. 
3. 

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Configuration
* Operating system: 
* Version of Telegram: 
* Version of the plugin: 

<details><summary><b>Logs</b></summary>
Insert the content of ArLog.txt here. (if necessary)<br>
(The log file is in the same directory with version.dll file)
</details>

**Comment by antifar** [comment] 2021-12-08 22:25
邮件已收到，祝好。^_^

**Comment by SpriteOvO** [comment] 2021-12-10 09:05
Duplicate of #96

**Closed by SpriteOvO** 2021-12-10 09:05 UTC
