### ISSUE TITLE
Support for WINE?

### ISSUE THREAD

**Issue by gunahub** [SpriteOvO/Telegram-Anti-Revoke#37] opened 2021-01-17 08:58 UTC
Hi. In linux I tried this using Wine For versions of Telegram Desktop 2.4.0 2.4.3, 2.4.4 and 2.5.1 (Windows 10 32 Bit)
But the Anti-Revoking doesn't seems to be working.
When I tried deleting it got deleted.
Any Ideas?
PS; I tried with the Latest release of Telegram-Anti-Revoke

**Comment by SpriteOvO** [comment] 2021-01-17 10:42
Could you check if ArLog.txt is created in the Telegram directory? If so, please post the content.

**Comment by gunahub** [comment] 2021-01-17 10:46
Nope. It only has log.txt
![image](https://user-images.githubusercontent.com/67857588/104838187-45fb9900-58df-11eb-8460-17a5d3de9b68.png)

**Comment by SpriteOvO** [comment] 2021-01-17 10:52
> Should I send its contents?

No, its Telegram's log file, not the plugin.

The problem is that `wine` is not preferentially loading the "fake" system dll `version.dll` in the current directory to make the plugin inject into Telegram. I will try to find a solution later.

**Comment by gunahub** [comment] 2021-01-17 10:54
> > Should I send its contents?
> 
> No, its Telegram's log file, not the plugin.
> 
> The problem is that `wine` doesn't preferentially loading the "fake" system dll `version.dll` in the current directory to make the plugin inject into Telegram. I will try to find a solution later.

Sure. Thanks for your time :)

**Comment by SpriteOvO** [comment] 2021-01-17 19:03
The plugin does have a way to work in `wine`, but it needs some patches.

I will consider and try to make the plugin directly compatible with `Linux` in the future, and if you need a patched version for `wine` now, I will send it in this issue.

**Comment by SpriteOvO** [comment] 2021-01-17 19:04
The plugin does have a way to work in `wine`, but it needs some patches.

I will consider and try to make the plugin directly compatible with `Linux` in the future, and if you need a patched version for `wine` now, I will send it in this issue.

**Comment by gunahub** [comment] 2021-01-18 17:25
Cool! Waiting for Linux plugin.

And Yeah It would be much helpful if I get the patch here.

**Comment by SpriteOvO** [comment] 2021-01-18 17:46
[TelegramAntiRevoke-3.0.0(Wine).zip](https://github.com/SpriteOvO/Telegram-Anti-Revoke/files/5831779/TelegramAntiRevoke-3.0.0.Wine.zip)

The patched version will be maintained in the `wine` branch of the repository.

After copying the `version.dll` file to the Telegram path, run the `wine` with this command:
`WINEDLLOVERRIDES="version=n,b" wine Telegram.exe`

**Comment by SpriteOvO** [comment] 2021-01-19 00:49
@gunahub Let me know if it works or not please.

**Comment by gunahub** [comment] 2021-01-19 02:41
It works like a charm!
The deleted tag appears only when I click that name again but thats not a big issue at all.
Thanks for your work!
![image](https://user-images.githubusercontent.com/67857588/104981030-df38c580-5a2d-11eb-8dc8-86e0c99d8b0b.png)

**Comment by SpriteOvO** [comment] 2021-01-19 02:54
> The deleted tag appears only when I click that name again

Yes, currently the tag will only be updated when Telegram gains focus, and this issue will be improved in the future, but it is a low priority.

I will close this issue and create a new one about the progress of the plugin support for `Linux`.

**Closed** 2021-01-19 02:55 UTC
Labels: enhancement, question

**Comment by SpriteOvO** [comment] 2021-01-19 03:02
Tracking issue for Linux support: #39
