### ISSUE TITLE
ADD ANTI EDIT MESSAGE !! [Feature Request] 

### ISSUE THREAD

**Issue by lecatos** [SpriteOvO/Telegram-Anti-Revoke#55] opened 2021-03-23 11:52 UTC
WE HAVE ANTI DELETE BUT NOT ANTI EDIT YET  !!!
IF SOMEONE WANT TO REALLY DELETE A MESSAGE TO MAKE SURE THAT IT'S ALSO DELETED ON OUR SIDE, THEY CAN JUST EDIT THE MESSAGE AND THEN IT WILL BE TRUELY DELETED !
IN THAT CASE, THE FEATURE WE CURRENTLY HAVE RIGHT NOW IS TOTALLY USELESS !!
WE WANT ANTI EDIT FEATURE !!!

PLEASE SUPPORT MY IDEA !

**Comment by SpriteOvO** [comment] 2021-03-23 11:57
Duplicate of #11

I can't think of a way to solve this problem because there is no way to get the content of uncached messages.

**Closed by SpriteOvO** 2021-03-23 11:57 UTC
