### ISSUE TITLE
[Bug report] InitDynamicData() failed in Telegram Desktop x86 (Version3.2.5)（在Telegram桌面版（版本3.2.5）中出现"InitDynamicData() failed"异常）

### ISSUE THREAD

**Issue by 19770214** [SpriteOvO/Telegram-Anti-Revoke#89] opened 2021-11-17 12:10 UTC
### Steps to reproduce
1.Open telegram 
2.wait sometimes
3.BOOM
（为防翻译出错加个汉语）
1.打开Telegram
2.等上一会儿
3.程序出错

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Configuration
* Operating system: Windows
* Version of Telegram: 3.2.5
* Version of the plugin: The lastest

（因为日志显示那里不知道为啥没有换行，我没写过html，也不太清楚GitHub Issue在哪上传文件，所以只能单独加个日志文件下载链接了）
Log file download link:https://onecloud.19770214.top/api/v3/file/source/243/ArLog.txt?sign=-hTNYnqCQTT2C8urhZIUKXSjOXebWsQNwbfZgHKOJ3E%3D%3A0
日志下载链接:https://onecloud.19770214.top/api/v3/file/source/243/ArLog.txt?sign=-hTNYnqCQTT2C8urhZIUKXSjOXebWsQNwbfZgHKOJ3E%3D%3A0

<details><summary><b>Logs</b></summary>
[2021-11-17 19:57:12.794] [Main] [info] [RealMain.cpp:32] Running. Version: "0.4.2", Platform: "x86"
[2021-11-17 19:57:12.797] [Main] [info] [IRuntime.cpp:27] [IRuntime] Telegram version: 3002005
[2021-11-17 19:57:33.920] [Main] [warning] [IUpdater.cpp:244] [Updater] Internet::HttpRequest() failed. (ByBridge)
[2021-11-17 19:57:33.920] [Main] [warning] [IUpdater.cpp:35] [Updater] GetDataByBridge() failed, try GetDataDirectly().
[2021-11-17 19:57:35.326] [Main] [info] [IUpdater.cpp:294] [Updater] Get data directly successed.
[2021-11-17 19:57:35.326] [Main] [info] [IUpdater.cpp:107] [Updater] No need to update. Local: 000004002, Latest: 000004002
[2021-11-17 19:57:35.326] [Main] [info] [IUpdater.cpp:56] [Updater] ParseResponse() successed. (Directly)
[2021-11-17 19:57:35.814] [Main] [info] [IRuntime.cpp:125] [IRuntime] InitDynamicData_MallocFree() succeeded.
[2021-11-17 19:57:35.990] [Main] [info] [IRuntime.cpp:126] [IRuntime] InitDynamicData_DestroyMessage() succeeded.
[2021-11-17 19:57:36.190] [Main] [info] [IRuntime.cpp:127] [IRuntime] InitDynamicData_EditedIndex() succeeded.
[2021-11-17 19:57:36.377] [Main] [info] [IRuntime.cpp:128] [IRuntime] InitDynamicData_SignedIndex() succeeded.
[2021-11-17 19:57:36.592] [Main] [info] [IRuntime.cpp:129] [IRuntime] InitDynamicData_ReplyIndex() succeeded.
[2021-11-17 19:57:36.838] [Main] [info] [IRuntime.cpp:130] [IRuntime] InitDynamicData_LangInstance() succeeded.
[2021-11-17 19:57:37.084] [Main] [warning] [IRuntime.cpp:1263] [IRuntime] Search toHistoryMessage index falied.
[2021-11-17 19:57:37.084] [Main] [warning] [IRuntime.cpp:131] [IRuntime] InitDynamicData_ToHistoryMessage() failed.
<br>
(The log file is in the same directory with version.dll file)
</details>

**Comment by SpriteOvO** [comment] 2021-11-17 13:09
Duplicate of #88

**Closed** 2021-11-17 13:09 UTC
