### ISSUE TITLE
[Feature Request] Show origin content if message being edited

### ISSUE THREAD

**Issue by lupohan44** [SpriteOvO/Telegram-Anti-Revoke#93] opened 2021-11-28 08:04 UTC
### Is your feature request related to a problem? Please describe.
N/A

### Describe the solution you'd like
Is it possible to show origin content if message being edited?

### Describe alternatives you've considered
N/A

### Additional context
N/A

**Comment by SpriteOvO** [comment] 2021-11-28 15:15
Duplicate of #11

**Closed by SpriteOvO** 2021-11-28 15:15 UTC
