### ISSUE TITLE
[Question] Deteled message disappeared after the program restart

### ISSUE THREAD

**Issue by PDxtXHd** [SpriteOvO/Telegram-Anti-Revoke#94] opened 2021-12-05 11:52 UTC
I updated this client to v3.2.5, the pugin is v0.4.3
The deleted message will disappear when I close the client and restart it:
![image](https://user-images.githubusercontent.com/54795848/144744650-7a47717f-f786-41fd-a336-9efba4da37b2.png)
![image](https://user-images.githubusercontent.com/54795848/144744685-a72da58d-f6ec-4565-a144-7217097f2ab4.png)
Is that a bug or feature?
I remember that in old versions deleted messages will still be there after restart, so I'm not sure the behavior now is a bug or feature on new versions?

**Comment by SpriteOvO** [comment] 2021-12-05 12:22
This is expected. The plugin just keeps the messages in the memory and does not have the ability to save and restore them from other storage.

**Comment by SpriteOvO** [comment] 2021-12-05 12:22
Duplicate of #1

**Closed by SpriteOvO** 2021-12-05 12:22 UTC
Labels: question
