### ISSUE TITLE
[Question] Anti-Anti-Revoke has emerged 

### ISSUE THREAD

**Issue by TechFa** [SpriteOvO/Telegram-Anti-Revoke#59] opened 2021-05-02 10:38 UTC
Anti-Anti-Revoke has emerged 
![image](https://user-images.githubusercontent.com/74394410/116810269-8244c380-ab75-11eb-95c8-d06c1ec6e664.png)

**Comment by SpriteOvO** [comment] 2021-05-02 10:40
Duplicate of #11.

**Closed by SpriteOvO** 2021-05-02 10:40 UTC
Labels: question
