### ISSUE TITLE
[Bug report] Crash on Telegram 3.3

### ISSUE THREAD

**Issue by mclovin-2k** [SpriteOvO/Telegram-Anti-Revoke#96] opened 2021-12-09 01:39 UTC
### Describe the bug
Crash on Telegram 3.3

### Steps to reproduce
1. Launch TAR-Launcher-x64.exe
2. 
3. 

### Expected behaviour
working

### Actual behaviour
crash

### Configuration
* Operating system: WINDOWS 10
* Version of Telegram: 3.3
* Version of the plugin: 0.4.3

<details><summary><b>Logs</b></summary>
[2021-12-09 09:34:20.157] [Main] [info] [RealMain.cpp:32] Running. Version: "0.4.3", Platform: "x64"
[2021-12-09 09:34:20.160] [Main] [info] [IRuntime.cpp:27] [IRuntime] Telegram version: 3003000
[2021-12-09 09:34:39.089] [Main] [warning] [IUpdater.cpp:244] [Updater] Internet::HttpRequest() failed. (ByBridge)
[2021-12-09 09:34:39.089] [Main] [warning] [IUpdater.cpp:35] [Updater] GetDataByBridge() failed, try GetDataDirectly().
[2021-12-09 09:34:40.040] [Main] [info] [IUpdater.cpp:294] [Updater] Get data directly successed.
[2021-12-09 09:34:40.040] [Main] [info] [IUpdater.cpp:107] [Updater] No need to update. Local: 000004003, Latest: 000004002
[2021-12-09 09:34:40.040] [Main] [info] [IUpdater.cpp:56] [Updater] ParseResponse() successed. (Directly)
[2021-12-09 09:34:40.161] [Main] [info] [IRuntime.cpp:125] [IRuntime] InitDynamicData_MallocFree() succeeded.
[2021-12-09 09:34:40.282] [Main] [warning] [IRuntime.cpp:446] [IRuntime] Search DestroyMessage failed.
[2021-12-09 09:34:40.282] [Main] [warning] [IRuntime.cpp:126] [IRuntime] InitDynamicData_DestroyMessage() failed.
[2021-12-09 09:34:40.282] [Main] [critical] [RealMain.cpp:51] [IRuntime] InitDynamicData() failed.
</details>

**Comment by undefined-moe** [comment] 2021-12-09 10:45
The same.
![image](https://user-images.githubusercontent.com/29992205/145382247-1ec60981-e0f7-4d8c-8f78-1e32559c4d33.png)

**Comment by dinghack** [comment] 2021-12-10 02:20
Me too

**Comment by Kiryusugar** [comment] 2021-12-10 05:47
Same issue. Seems to be signature matching problem.

### Configuration
Operating system: WINDOWS 10
Version of Telegram: 3.3.0 portable x64
Version of the plugin: 0.4.3

### Decompiled source
```
telegram portable x64 v3.3.0

00007FF75B6BADD0 | 48:895424 10             | mov qword ptr ss:[rsp+10],rdx           |
00007FF75B6BADD5 | 53                       | push rbx                                |
00007FF75B6BADD6 | 48:83EC 30               | sub rsp,30                              |
00007FF75B6BADDA | 48:8BD9                  | mov rbx,rcx                             |
00007FF75B6BADDD | 48:8D5424 48             | lea rdx,qword ptr ss:[rsp+48]           |
00007FF75B6BADE2 | 48:81C1 00010000         | add rcx,100                             |
00007FF75B6BADE9 | E8 C2F890FF              | call telegram.7FF75AFCA6B0              |
00007FF75B6BADEE | 48:8B5424 48             | mov rdx,qword ptr ss:[rsp+48]           |
00007FF75B6BADF3 | C64424 40 00             | mov byte ptr ss:[rsp+40],0              |
00007FF75B6BADF8 | 48:85D2                  | test rdx,rdx                            |
00007FF75B6BADFB | 0F84 BC000000            | je telegram.7FF75B6BAEBD                |
00007FF75B6BAE01 | 48:8D4424 40             | lea rax,qword ptr ss:[rsp+40]           |
00007FF75B6BAE06 | 48:895C24 28             | mov qword ptr ss:[rsp+28],rbx           |
00007FF75B6BAE0B | 4C:8D4424 20             | lea r8,qword ptr ss:[rsp+20]            |
00007FF75B6BAE10 | 48:894424 20             | mov qword ptr ss:[rsp+20],rax           |
00007FF75B6BAE15 | 48:8BCB                  | mov rcx,rbx                             |
00007FF75B6BAE18 | E8 F3B1FDFF              | call telegram.7FF75B696010              |
00007FF75B6BAE1D | 807C24 40 00             | cmp byte ptr ss:[rsp+40],0              |
00007FF75B6BAE22 | 74 60                    | je telegram.7FF75B6BAE84                |
00007FF75B6BAE24 | 48:8B5424 48             | mov rdx,qword ptr ss:[rsp+48]           |
00007FF75B6BAE29 | 48:85D2                  | test rdx,rdx                            |
00007FF75B6BAE2C | 0F84 B2000000            | je telegram.7FF75B6BAEE4                |
00007FF75B6BAE32 | 48:8D8B 380D0000         | lea rcx,qword ptr ds:[rbx+D38]          |
00007FF75B6BAE39 | E8 C243F6FF              | call telegram.7FF75B61F200              |
00007FF75B6BAE3E | 48:85C0                  | test rax,rax                            |
00007FF75B6BAE41 | 74 41                    | je telegram.7FF75B6BAE84                |
00007FF75B6BAE43 | 48:8B00                  | mov rax,qword ptr ds:[rax]              |
00007FF75B6BAE46 | 48:8B00                  | mov rax,qword ptr ds:[rax]              |
00007FF75B6BAE49 | 48:85C0                  | test rax,rax                            |
00007FF75B6BAE4C | 0F84 B9000000            | je telegram.7FF75B6BAF0B                |
00007FF75B6BAE52 | 48:8B5424 48             | mov rdx,qword ptr ss:[rsp+48]           |
00007FF75B6BAE57 | 48:85D2                  | test rdx,rdx                            |
00007FF75B6BAE5A | 0F84 D2000000            | je telegram.7FF75B6BAF32                |
00007FF75B6BAE60 | 48:3BC2                  | cmp rax,rdx                             |
00007FF75B6BAE63 | 74 24                    | je telegram.7FF75B6BAE89                |
00007FF75B6BAE65 | 48:8D4C24 40             | lea rcx,qword ptr ss:[rsp+40]           |
00007FF75B6BAE6A | 48:895C24 28             | mov qword ptr ss:[rsp+28],rbx           |
00007FF75B6BAE6F | 48:894C24 20             | mov qword ptr ss:[rsp+20],rcx           |
00007FF75B6BAE74 | 4C:8D4424 20             | lea r8,qword ptr ss:[rsp+20]            |
00007FF75B6BAE79 | 48:8BCB                  | mov rcx,rbx                             |
00007FF75B6BAE7C | 48:8BD0                  | mov rdx,rax                             |
00007FF75B6BAE7F | E8 8CB1FDFF              | call telegram.7FF75B696010              |
00007FF75B6BAE84 | 48:8B5424 48             | mov rdx,qword ptr ss:[rsp+48]           |
00007FF75B6BAE89 | 48:85D2                  | test rdx,rdx                            |
00007FF75B6BAE8C | 0F84 C7000000            | je telegram.7FF75B6BAF59                |
// Here 
00007FF75B6BAE92 | 48:8B5A 18               | mov rbx,qword ptr ds:[rdx+18]           |
00007FF75B6BAE96 | 48:85DB                  | test rbx,rbx                            |
00007FF75B6BAE99 | 0F84 E1000000            | je telegram.7FF75B6BAF80                |
00007FF75B6BAE9F | 48:8D8B F8000000         | lea rcx,qword ptr ds:[rbx+F8]           |
00007FF75B6BAEA6 | E8 B5990800              | call telegram.7FF75B744860              |
00007FF75B6BAEAB | 84C0                     | test al,al                              |
00007FF75B6BAEAD | 74 08                    | je telegram.7FF75B6BAEB7                |
00007FF75B6BAEAF | 48:8BCB                  | mov rcx,rbx                             |
00007FF75B6BAEB2 | E8 D9E60300              | call telegram.7FF75B6F9590              |
00007FF75B6BAEB7 | 48:83C4 30               | add rsp,30                              |
00007FF75B6BAEBB | 5B                       | pop rbx                                 |
00007FF75B6BAEBC | C3                       | ret                                     |

IRuntime::InitDynamicData_DestroyMessage()
Old: 48 8B 5A 18 48 85 DB 0F 84 ?? ?? ?? ?? 48 8B CB E8 ?? ?? ?? ?? 80 BB ?? ?? ?? ?? 00
                                               !!
New: 48 8B 5A 18 48 85 DB 0F 84 ?? ?? ?? ?? 48 8D 8B F8 00 00 00 E8 ?? ?? ?? ?? 
```
</details>

**Comment by saeex** [comment] 2021-12-10 08:23
same problem telegram 3.3 X64

**Comment by SpriteOvO** [comment] 2021-12-10 09:06
Duplicate of #92

**Closed as completed by SpriteOvO** 2021-12-10 09:06 UTC
Labels: duplicate
