### ISSUE TITLE
[Feature Request] 請問能增加匯出已經刪除對話訊息的功能嗎? Could you add the function of exporting deleted dialog messages?

### ISSUE THREAD

**Issue by teekahchic** [SpriteOvO/Telegram-Anti-Revoke#85] opened 2021-11-04 12:19 UTC
可以看見刪除的對話.
但是不能保存.

### Is your feature request related to a problem? Please describe.
A clear and concise description of what the problem is.

**Comment by SpriteOvO** [comment] 2021-11-04 12:22
Duplicate of #1

**Closed by SpriteOvO** 2021-11-04 12:22 UTC
Labels: duplicate
