### ISSUE TITLE
[Feature Request] "Revoking" edited messages

### ISSUE THREAD

**Issue by Alispezzate** [SpriteOvO/Telegram-Anti-Revoke#75] opened 2021-09-06 03:44 UTC
The functionality of the plugin is easily avoidable by simply editing the message instead of deleting it, for example I can edit a message to be completely different from how it was before so it's like deleting it.

I suggest to implement a way to see the edits of messages, for example like it happens with git diff or in notion updates (I can provide an example if needed)

An other way would be to for example create a new message instead of editing the old one but I guess it would be more complicated.

**Comment by SpriteOvO** [comment] 2021-09-06 09:44
In fact it is also complicated to record the edit history of each message. Telegram does not cache each message content unless the chat of the message is active (the chat was recently opened and you are browsing near the message).

Even if the trouble with record is solved, displaying edit history in messages through the plugin is not a simple task, and that's not even considering non-text messages.

And BTW this issue is a duplicate of #11.

**Closed** 2021-09-06 09:45 UTC
Labels: duplicate
