### ISSUE TITLE
for telegram version 2.8.4 x64 does not work [Bug report] 

### ISSUE THREAD

**Issue by zloishax** [SpriteOvO/Telegram-Anti-Revoke#62] opened 2021-07-02 06:20 UTC
### Steps to reproduce
1. 
2. 
3. 

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Configuration
* Operating system: 
* Version of Telegram: 
* Version of the plugin: 

<details><summary><b>Logs</b></summary>
Insert the content of ArLog.txt here. (if necessary)<br>
(The log file is in the same directory with version.dll file)
</details>

**Comment by zloishax** [comment] 2021-07-02 06:21
win 10

**Comment by SpriteOvO** [comment] 2021-07-02 06:59
Duplicate of #46

**Closed by SpriteOvO** 2021-07-02 06:59 UTC
