### ISSUE TITLE
Plugin does not work  with Telegram version 3.1.8 X64  Protable

### ISSUE THREAD

**Issue by tjsky** [SpriteOvO/Telegram-Anti-Revoke#82] opened 2021-10-09 06:51 UTC
### Describe the bug
1、Plugin does not work  with latest Telegram version 3.1.8 X64 （Protable）
messages still being  revoked by the server.

2、The error appears when someone delete any msg in chat with latest Telegram version 3.1.8 X64( Installed）
![_20213309023300](https://user-images.githubusercontent.com/7272911/136647077-e1eabf22-0bd3-4467-a792-5f5e8f4ff75b.png)

### Configuration
* Operating system: WIN10 20H1
* Version of Telegram: 3.1.8 X64（Installed&Protable）
* Version of the plugin: 0.4.1

**Comment by SpriteOvO** [comment] 2021-10-09 06:52
Duplicate of #79

**Closed by SpriteOvO** 2021-10-09 06:52 UTC
Labels: duplicate
